name: build https://html-now.github.io/

on:
  schedule:
    - cron: '19 2 * * *'
  workflow_dispatch:

defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Run https://html-now.github.io/ build
        id: incoming
        run: |
          make -B
      - uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
          git-user-signingkey: true
          git-commit-gpgsign: true
      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          title: Update https://html-now.github.io/
          commit-message: Update https://html-now.github.io/
          committer: sideshowbarkerbot <sideshowbarker+sideshowbarkerbot@gmail.com>
          author: sideshowbarkerbot <sideshowbarker+sideshowbarkerbot@gmail.com>
          assignees: sideshowbarker
          reviewers: sideshowbarker
          branch: create-pull-request/patch-site
          delete-branch: true
      - name: Log pull request URL
        run: |
          echo "Pull request URL: ${{ steps.cpr.outputs.pull-request-url }}"
